from dotenv import load_dotenv
import os
import json

load_dotenv()


MONGODB_HOST = os.environ['MONGODB_HOST']
MONGODB_NAME = os.environ['MONGODB_NAME']

UNIX_SOCKET_ADDRESS = os.environ['UNIX_SOCKET_ADDRESS']
WEBSOCKET_HOST = os.environ['WEBSOCKET_HOST']
WEBSOCKET_PORT = os.environ['WEBSOCKET_PORT']

BINANCE_API_KEY = os.environ['BINANCE_API_KEY']
BINANCE_API_SECRET = os.environ['BINANCE_API_SECRET']
TESTNET_BINANCE_API_KEY = os.environ['TESTNET_BINANCE_API_KEY']
TESTNET_BINANCE_API_SECRET = os.environ['TESTNET_BINANCE_API_SECRET']

MODE = 'EMULATOR'
SYMBOLS_EXCHANGE_INITIALIZATION = False
MARGIN_SIZE = 19
LEVERAGE = 20
MAX_ACTIVE_TRADES = 20

WINDOW_SIZE = 200
SYMBOLS = []
with open('symbols.json') as file:
    SYMBOLS = json.load(file)